name: Angular Test CI
on:
  push:
    branches: [ main ]
    paths:
      - "diagnostics-app/**"
  pull_request:
    branches: [ main ]
    paths:
      - "diagnostics-app/**"
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: diagnostics-app
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run script:ci
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
